# imports

In [2]:
import duckdb
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

conn = duckdb.connect('../../database/financial_data.duckdb')

query = "SELECT * FROM gold_ml_features WHERE asset_symbol = 'AAPL' AND interval = '1h' ORDER BY date"
df = conn.execute(query).df()

print(f"Total Rows with Macro Data: {len(df)}")
df.tail()

Total Rows with Macro Data: 6189

,asset_symbol,asset_class,exchange,interval,date,open,high,low,close,volume,...,log_returns,hl_ratio,close_position,prev_close,prev_volume,prev_high,prev_low,dxy_close,vix_close,tnx_close
6184,AAPL,Stock,Yahoo Finance,1h,2026-05-11 17:30:00,291.939911,292.980011,291.725006,291.739990,2587000.0,...,-0.000685,0.004302,0.011940,291.940002,3556324.0,292.704987,290.630005,97.911003,18.160000,4.408
6185,AAPL,Stock,Yahoo Finance,1h,2026-05-11 17:30:00,291.939911,292.980011,291.725006,291.739990,2587000.0,...,-0.000685,0.004302,0.011940,291.940002,3556324.0,292.704987,290.630005,97.911003,18.160000,4.404
6186,AAPL,Stock,Yahoo Finance,1h,2026-05-11 18:30:00,291.739990,292.209900,290.859985,292.149994,2874040.0,...,0.001404,0.004621,0.955622,291.739990,2587000.0,292.980011,291.725006,97.955002,18.280001,4.404
6187,AAPL,Stock,Yahoo Finance,1h,2026-05-11 18:30:00,291.739990,292.209900,290.859985,292.149994,2874040.0,...,0.001404,0.004621,0.955622,291.739990,2587000.0,292.980011,291.725006,97.955002,18.280001,4.410
6188,AAPL,Stock,Yahoo Finance,1h,2026-05-11 19:30:00,292.145905,292.799988,291.809998,292.739990,3307424.0,...,0.002017,0.003382,0.939396,292.149994,2874040.0,292.209900,290.859985,97.960999,18.360001,4.410

In [3]:
print("--- AAPL 1h Date Range ---")
print(conn.execute("SELECT MIN(date), MAX(date) FROM gold_financial_analytics WHERE asset_symbol='AAPL' AND interval='1h'").df())

print("\n--- Macro 1h Date Range ---")
print(conn.execute("SELECT MIN(date), MAX(date) FROM clean_macro_features WHERE interval='1h'").df())

--- AAPL 1h Date Range ---
            min(date)           max(date)
0 2024-04-03 13:30:00 2026-05-11 19:30:00

--- Macro 1h Date Range ---
            min(date)           max(date)
0 2024-06-13 04:00:00 2026-05-14 10:00:00

In [ ]:
print("--- BTC 1h Sample ---")
display(conn.execute("SELECT date FROM gold_financial_analytics WHERE asset_symbol='BTC' AND interval='1h' LIMIT 5").df())

print("\n--- Macro 1h Sample ---")
display(conn.execute("SELECT date FROM clean_macro_features WHERE interval='1h' LIMIT 5").df())

--- BTC 1h Sample ---

                 date
0 2020-03-25 10:00:00
1 2020-03-25 11:00:00
2 2020-03-25 12:00:00
3 2020-03-25 13:00:00
4 2020-03-25 14:00:00

--- Macro 1h Sample ---

                 date
0 2024-06-13 07:00:00
1 2024-06-13 08:00:00
2 2024-06-13 09:00:00
3 2024-06-13 10:00:00
4 2024-06-13 11:00:00

In [5]:
conn.close()